-- Supabase Migration Schema
-- Copy and paste this script into your Supabase SQL Editor (Dashboard > SQL Editor > New Query) and click Run.

-- 1. Create inventory table
CREATE TABLE IF NOT EXISTS inventory (
  id text PRIMARY KEY,                -- Maps to Firebase doc.id / unique identifier
  "Part ID" text UNIQUE,
  "Department" text,
  "Plant" text,
  "Main Category" text,
  "Sub Category" text,
  "Brand" text,
  "Model" text,
  "Description" text,
  "Area" text,
  "Location" text,
  "Position" text,
  "Actual" text,                     -- Kept as text to match existing JavaScript data structure
  "Min" text,
  "Max" text,
  "COST" text,
  "VENDOR" text,
  "DELIVER TIME" text,
  "DELIVER UNIT" text,
  "Install Year" text,
  "Expected Life" text,
  "Replace Plan" text,
  "CLASS" text,
  "imageUrl" text,
  "_updatedAt" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "_device" text,
  "_updatedBy" text
);

-- Enable Realtime for inventory table
alter publication supabase_realtime add table inventory;

-- 2. Create logs table
CREATE TABLE IF NOT EXISTS logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text,
  "partId" text,
  msg text,
  note text,
  ts timestamp with time zone DEFAULT timezone('utc'::text, now()),
  device text,
  "user" text,
  undo_data jsonb
);

-- Migration for existing database table:
-- ALTER TABLE logs ADD COLUMN IF NOT EXISTS undo_data jsonb;

-- Enable Realtime for logs table
alter publication supabase_realtime add table logs;

-- 3. Create store_meta table for ID Counter
CREATE TABLE IF NOT EXISTS store_meta (
  key text PRIMARY KEY,
  current integer NOT NULL DEFAULT 0
);

-- Seed metadata counter
INSERT INTO store_meta (key, current)
VALUES ('partIdCounter', 0)
ON CONFLICT (key) DO NOTHING;

-- 4. Atomic Function to generate next Part ID (replaces Firestore Transaction safety)
CREATE OR REPLACE FUNCTION get_next_part_id()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  next_num integer;
  max_num integer;
BEGIN
  -- Get the maximum number from current inventory matching 'SPFL-C-XXXX' format
  SELECT COALESCE(MAX(CAST(substring("Part ID" from '(?i)^SPFL-C-(\d+)$') AS integer)), 0)
  INTO max_num
  FROM inventory;

  -- Ensure partIdCounter is at least max_num
  INSERT INTO store_meta (key, current)
  VALUES ('partIdCounter', max_num)
  ON CONFLICT (key) DO UPDATE
  SET current = GREATEST(store_meta.current, max_num);

  -- Increment and return
  UPDATE store_meta
  SET current = current + 1
  WHERE key = 'partIdCounter'
  RETURNING current INTO next_num;

  RETURN next_num;
END;
$$;

-- 5. Atomic Function to adjust stock (replaces Firestore Transaction safety)
CREATE OR REPLACE FUNCTION adjust_stock_v2(
  item_id text,
  qty double precision,
  mode text,
  new_loc text,
  new_pos text,
  device_id text,
  user_name text
)
RETURNS double precision
LANGUAGE plpgsql
AS $$
DECLARE
  current_actual double precision;
  new_actual double precision;
BEGIN
  -- Lock row for concurrency safety
  SELECT CAST(COALESCE(NULLIF("Actual", ''), '0') AS double precision) INTO current_actual
  FROM inventory
  WHERE id = item_id
  FOR UPDATE;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Item not found';
  END IF;
  
  IF qty = 0 THEN
    new_actual := current_actual;
  ELSIF mode = 'out' THEN
    IF current_actual <= 0 AND qty > 0 THEN
      RAISE EXCEPTION 'ZERO_STOCK';
    END IF;
    IF qty > current_actual THEN
      RAISE EXCEPTION 'OVER_STOCK';
    END IF;
    new_actual := GREATEST(0, current_actual - qty);
  ELSE
    new_actual := current_actual + qty;
  END IF;
  
  UPDATE inventory
  SET "Actual" = CAST(new_actual AS text),
      "Location" = COALESCE(new_loc, "Location"),
      "Position" = COALESCE(new_pos, "Position"),
      "_updatedAt" = NOW(),
      "_device" = device_id,
      "_updatedBy" = user_name
  WHERE id = item_id;
  
  RETURN new_actual;
END;
$$;

-- 4. Purchase Request tables (pr.html)
-- Column names mirror the original Firestore record keys. PR No. / PO No. are
-- text (Firestore stored imported ones as numbers; the app already String()s them).
-- Post Date stays text: data mixes dd-mm-yy and Excel serials.
CREATE TABLE IF NOT EXISTS pr_records (
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "PR No." text UNIQUE,
  "PO No." text,
  "Creator" text,
  "PR Title" text,
  "Section" text,
  "Item Desc" text,
  "Category" text,
  "Work Class" text,
  "Plan Type" text,
  "Status" text,
  "Deliv. Status" text,
  "PR_Vendor" text,
  "PO_Vendor" text,
  "PR Amount" numeric,
  "PO Amount" numeric,
  "Currency Key" text,
  "Budget code" text,
  "Post Date" text,
  "Purchaser" text,
  "Entry by" text,
  "Request Type" text,
  "Delivery Date" text,
  "Quotation No" text,
  "Discount" numeric DEFAULT 0,
  "Items" jsonb,
  "createdAt" timestamptz DEFAULT now(),
  "importedAt" timestamptz,
  device text
);

CREATE TABLE IF NOT EXISTS pr_import_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mode text,
  count integer,
  ts timestamptz DEFAULT now(),
  device text
);

alter publication supabase_realtime add table pr_records;

-- If RLS is enabled on this project, mirror the policies used for inventory/logs:
-- ALTER TABLE pr_records ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "pr_records authenticated all" ON pr_records FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- ALTER TABLE pr_import_logs ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "pr_import_logs authenticated all" ON pr_import_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
